/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of DES.xs. Do not edit this file, edit DES.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "DES.xs"
/*
*  cross-platform and mod_ssl-safe code modifications are Copyright (C)
*  2000 W3Works, LLC.  All rights reserved.
*/

/*
 *	Copyright (C) 1995, 1996 Systemics Ltd (http://www.systemics.com/)
 *	All rights reserved.
 */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

typedef unsigned char i8;
typedef unsigned long i32;

#include "_des.h"

#ifndef sv_undef
#define sv_undef  PL_sv_undef
#endif

#line 34 "DES.c"

XS(XS_Crypt__DES_expand_key); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__DES_expand_key)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Crypt::DES::expand_key(key)");
    {
	char *	key;
	STRLEN	key_len;
	char *	RETVAL;
	dXSTARG;
#line 32 "DES.xs"
	{
		des_ks	ks;

		key = (char *) SvPV(ST(0), key_len);
		if (key_len != sizeof(des_user_key))
			croak("Invalid key");

		perl_des_expand_key((i8 *)key, ks);

		ST(0) = sv_2mortal(newSVpv((char *)ks, sizeof(ks)));
	}
#line 59 "DES.c"
    }
    XSRETURN(1);
}


XS(XS_Crypt__DES_crypt); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__DES_crypt)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Crypt::DES::crypt(input, output, ks, enc_flag)");
    {
	char *	input;
	SV *	output = ST(1);
	char *	ks;
	int	enc_flag = (int)SvIV(ST(3));
	STRLEN	input_len;
	STRLEN	output_len;
	STRLEN	ks_len;
#line 54 "DES.xs"
	{
		input = (char *) SvPV(ST(0), input_len);
		if (input_len != 8)
			croak("input must be 8 bytes long");

		ks = (char *) SvPV(ST(2), ks_len);
		if (ks_len != sizeof(des_ks))
			croak("Invalid key schedule");

		if (output == &sv_undef)
			output = sv_newmortal();
		output_len = 8;

		if (!SvUPGRADE(output, SVt_PV))
			croak("cannot use output argument as lvalue");

		perl_des_crypt(input, SvGROW(output, output_len), (i32 *)ks, enc_flag);

		SvCUR_set(output, output_len);
		*SvEND(output) = '\0';
		(void) SvPOK_only(output);
		SvTAINT(output);

		ST(0) = output;
	}
#line 105 "DES.c"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Crypt__DES); /* prototype to pass -Wmissing-prototypes */
XS(boot_Crypt__DES)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Crypt::DES::expand_key", XS_Crypt__DES_expand_key, file);
        newXS("Crypt::DES::crypt", XS_Crypt__DES_crypt, file);
    XSRETURN_YES;
}

