/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of SHA.xs. Do not edit this file, edit SHA.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "SHA.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "src/sha.c"
#include "src/hmac.c"

static int ix2alg[] =
	{1,1,1,224,224,224,256,256,256,384,384,384,512,512,512};

#line 21 "SHA.c"
#include "src/sha.h"
#include "src/hmac.h"
#ifndef INT2PTR
#define INT2PTR(p, i) (p) (i)
#endif

XS(XS_Digest__SHA_shaclose); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shaclose)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Digest::SHA::shaclose(s)");
    {
	SHA *	s;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "SHAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    s = INT2PTR(SHA *,tmp);
	}
	else
	    Perl_croak(aTHX_ "s is not of type SHAPtr");

	RETVAL = shaclose(s);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_shadump); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shadump)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Digest::SHA::shadump(file, s)");
    {
	char *	file = (char *)SvPV_nolen(ST(0));
	SHA *	s;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(1), "SHAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    s = INT2PTR(SHA *,tmp);
	}
	else
	    Perl_croak(aTHX_ "s is not of type SHAPtr");

	RETVAL = shadump(file, s);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_shadup); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shadup)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Digest::SHA::shadup(s)");
    {
	SHA *	s;
	SHA *	RETVAL;

	if (sv_derived_from(ST(0), "SHAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    s = INT2PTR(SHA *,tmp);
	}
	else
	    Perl_croak(aTHX_ "s is not of type SHAPtr");

	RETVAL = shadup(s);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "SHAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_shaload); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shaload)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Digest::SHA::shaload(file)");
    {
	char *	file = (char *)SvPV_nolen(ST(0));
	SHA *	RETVAL;

	RETVAL = shaload(file);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "SHAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_shaopen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shaopen)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Digest::SHA::shaopen(alg)");
    {
	int	alg = (int)SvIV(ST(0));
	SHA *	RETVAL;

	RETVAL = shaopen(alg);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "SHAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_sharewind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_sharewind)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Digest::SHA::sharewind(s)");
    {
	SHA *	s;

	if (sv_derived_from(ST(0), "SHAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    s = INT2PTR(SHA *,tmp);
	}
	else
	    Perl_croak(aTHX_ "s is not of type SHAPtr");

	sharewind(s);
    }
    XSRETURN_EMPTY;
}


XS(XS_Digest__SHA_shawrite); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shawrite)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Digest::SHA::shawrite(bitstr, bitcnt, s)");
    {
	unsigned char *	bitstr = (unsigned char *)SvPV_nolen(ST(0));
	unsigned long	bitcnt = (unsigned long)SvUV(ST(1));
	SHA *	s;
	unsigned long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(2), "SHAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(2)));
	    s = INT2PTR(SHA *,tmp);
	}
	else
	    Perl_croak(aTHX_ "s is not of type SHAPtr");

	RETVAL = shawrite(bitstr, bitcnt, s);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_sha1); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_sha1)
{
    dXSARGS;
    dXSI32;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 72 "SHA.xs"
	int i;
	unsigned char *data;
	STRLEN len;
	SHA *state;
	char *result;
#line 203 "SHA.c"
#line 78 "SHA.xs"
	if ((state = shaopen(ix2alg[ix])) == NULL)
		XSRETURN_UNDEF;
	for (i = 0; i < items; i++) {
		data = (unsigned char *) (SvPV(ST(i), len));
		shawrite(data, len << 3, state);
	}
	shafinish(state);
	len = 0;
	if (ix % 3 == 0) {
		result = (char *) shadigest(state);
		len = shadsize(state);
	}
	else if (ix % 3 == 1)
		result = shahex(state);
	else
		result = shabase64(state);
	ST(0) = sv_2mortal(newSVpv(result, len));
	shaclose(state);
	XSRETURN(1);
#line 224 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA_hmac_sha1); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_hmac_sha1)
{
    dXSARGS;
    dXSI32;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 117 "SHA.xs"
	int i;
	unsigned char *key;
	unsigned char *data;
	STRLEN len;
	HMAC *state;
	char *result;
#line 246 "SHA.c"
#line 124 "SHA.xs"
	key = (unsigned char *) (SvPV(ST(items-1), len));
	if ((state = hmacopen(ix2alg[ix], key, len)) == NULL)
		XSRETURN_UNDEF;
	for (i = 0; i < items - 1; i++) {
		data = (unsigned char *) (SvPV(ST(i), len));
		hmacwrite(data, len << 3, state);
	}
	hmacfinish(state);
	len = 0;
	if (ix % 3 == 0) {
		result = (char *) hmacdigest(state);
		len = shadsize(state->osha);
	}
	else if (ix % 3 == 1)
		result = hmachex(state);
	else
		result = hmacbase64(state);
	ST(0) = sv_2mortal(newSVpv(result, len));
	hmacclose(state);
	XSRETURN(1);
#line 268 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA_hashsize); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_hashsize)
{
    dXSARGS;
    dXSI32;
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(self)", GvNAME(CvGV(cv)));
    SP -= items;
    {
	SV *	self = ST(0);
#line 152 "SHA.xs"
	SHA *state;
	int result;
#line 288 "SHA.c"
#line 155 "SHA.xs"
	state = INT2PTR(SHA *, SvIV(SvRV(SvRV(self))));
	result = shadsize(state) << 3;
	if (ix == 1 && result == 160)
		result = 1;
	ST(0) = sv_2mortal(newSViv(result));
	XSRETURN(1);
#line 296 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_add)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Digest::SHA::add(self, ...)");
    SP -= items;
    {
	SV *	self = ST(0);
#line 166 "SHA.xs"
	int i;
	unsigned char *data;
	STRLEN len;
	SHA *state;
#line 317 "SHA.c"
#line 171 "SHA.xs"
	state = INT2PTR(SHA *, SvIV(SvRV(SvRV(self))));
	for (i = 1; i < items; i++) {
		data = (unsigned char *) (SvPV(ST(i), len));
		shawrite(data, len << 3, state);
	}
	XSRETURN(1);
#line 325 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA_digest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_digest)
{
    dXSARGS;
    dXSI32;
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(self)", GvNAME(CvGV(cv)));
    SP -= items;
    {
	SV *	self = ST(0);
#line 186 "SHA.xs"
	STRLEN len;
	SHA *state;
	char *result;
#line 346 "SHA.c"
#line 190 "SHA.xs"
	state = INT2PTR(SHA *, SvIV(SvRV(SvRV(self))));
	shafinish(state);
	len = 0;
	if (ix == 0) {
		result = (char *) shadigest(state);
		len = shadsize(state);
	}
	else if (ix == 1)
		result = shahex(state);
	else
		result = shabase64(state);
	ST(0) = sv_2mortal(newSVpv(result, len));
	sharewind(state);
	XSRETURN(1);
#line 362 "SHA.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Digest__SHA); /* prototype to pass -Wmissing-prototypes */
XS(boot_Digest__SHA)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

    {
        CV * cv ;

        newXSproto("Digest::SHA::shaclose", XS_Digest__SHA_shaclose, file, "$");
        newXSproto("Digest::SHA::shadump", XS_Digest__SHA_shadump, file, "$$");
        newXSproto("Digest::SHA::shadup", XS_Digest__SHA_shadup, file, "$");
        newXSproto("Digest::SHA::shaload", XS_Digest__SHA_shaload, file, "$");
        newXSproto("Digest::SHA::shaopen", XS_Digest__SHA_shaopen, file, "$");
        newXSproto("Digest::SHA::sharewind", XS_Digest__SHA_sharewind, file, "$");
        newXSproto("Digest::SHA::shawrite", XS_Digest__SHA_shawrite, file, "$$$");
        cv = newXS("Digest::SHA::sha512_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 13 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha1_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 2 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 14 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha224_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 4 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha224", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 3 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha256_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 7 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha384", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 9 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha384_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 10 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha224_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 5 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha256_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 8 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha1", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 12 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha1_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha256", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 6 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha384_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 11 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha1_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 2 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha1", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 14 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha256_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 7 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 12 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha1_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha256", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 6 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha224", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 3 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha224_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 4 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha384", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 9 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha256_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 8 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha384_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 11 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha384_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 10 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha224_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 5 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 13 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::algorithm", XS_Digest__SHA_hashsize, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, "$") ;
        cv = newXS("Digest::SHA::hashsize", XS_Digest__SHA_hashsize, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, "$") ;
        newXSproto("Digest::SHA::add", XS_Digest__SHA_add, file, "$;@");
        cv = newXS("Digest::SHA::digest", XS_Digest__SHA_digest, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, "$") ;
        cv = newXS("Digest::SHA::Hexdigest", XS_Digest__SHA_digest, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, "$") ;
        cv = newXS("Digest::SHA::B64digest", XS_Digest__SHA_digest, file);
        XSANY.any_i32 = 2 ;
        sv_setpv((SV*)cv, "$") ;
    }
    XSRETURN_YES;
}

